version: '2'

services:
  backend-application:
    build: './BackendApplication'
    ports:
      - "8081:8081"
  user-application:
    build: './UserApplication'
    depends_on:
      - backend-application
    ports:
      - "8080:80"
