version: '2'
services:
    frontend:
        build: './UserApplication'
       
        ports:
            - "8080:80"
    backend:
        build: './BackendApplication'
        depends_on:
            - frontend
        ports:
            - 8081:8081
    