version: '2'

services:
  backend-application:
    container_name: 'backend-application'
    build: './BackendApplication'
    network_mode: 'host'
  user-application:
    container_name: 'user-application'
    build: './UserApplication'
    depends_on:
      - backend-application
    network_mode: 'host'
